import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Search_Bar from '@/components/search_bar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Search for movies!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Movie Search
        </h1>
        <Search_Bar />
      </div>
    </>
  )
}
