import Head from 'next/head'
import Search_Bar from '@/components/search_bar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie Searcher | Search for movies!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="layout">
        <h1>
          Movie Searcher
        </h1>
        <Search_Bar />
      </div>
      <style jsx>{`
      .layout {
        margin: 30vh;
        margin-top: 40vh;
    
        display: flex;
        flex-direction: column;
      }
      `}</style>
    </>
  )
}
