import Head from 'next/head'
import Search_Bar from '@/components/search_bar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie Searcher | Search for movies!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container vh-100 d-flex flex-column justify-content-center align-items-center">
        <h1>
          Movie Searcher
        </h1>
        <Search_Bar className="search"/>
      </div>
    </>
  )
}
